title: Recompiling.net
description: "while(true): think; compile your thoughs;"
author:
  name: "Recompiling.net"
  email: ""
  url: "https://recompiling-net.github.io/hacker-blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Recompiling"
year : "2024"
